export const en = {
  metaTitle: 'Watad Admin',
  brand: { name: 'Watad Petroleum', sub: 'Admin dashboard' },
  nav: {
    overview: 'Overview',
    prices: 'Prices',
    stations: 'Stations',
    viewSite: 'View site',
    signOut: 'Sign out',
    otherLang: 'العربية',
    menu: 'Menu',
    closeMenu: 'Close menu',
  },
  login: {
    title: 'Sign in',
    sub: 'See who visits the site and update prices and stations.',
    password: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    wrong: 'Wrong password.',
    tooMany: 'Too many attempts. Try again in a few minutes.',
    network: "Can't reach the server. Check that it's running.",
  },
  common: {
    save: 'Save changes',
    saving: 'Saving…',
    saved: 'Changes saved',
    discard: 'Discard changes',
    unsaved: 'You have unsaved changes',
    allSaved: 'Everything is saved',
    delete: 'Delete',
    moveUp: 'Move up',
    moveDown: 'Move down',
    loading: 'Loading…',
    loadError: "Couldn't load the data.",
    retry: 'Try again',
    saveError: "Couldn't save. Check your connection and try again.",
    confirmDelete: 'Delete this item?',
    arabic: 'Arabic',
    english: 'English',
    noData: 'No data yet',
  },
  overview: {
    title: 'Overview',
    sub: 'Visits to the public site. Updates every 30 seconds.',
    refresh: 'Refresh',
    visitors: 'Unique visitors',
    visitorsNote: 'Each browser counts once',
    totalViews: 'Page views',
    totalViewsNote: 'All time',
    last7: 'Last 7 days',
    today: 'Today',
    visitorsCount: '{n} visitors',
    chartTitle: 'Daily visits',
    series: { views: 'Page views', visitors: 'Visitors' },
    range: { 7: '7 days', 30: '30 days', 90: '90 days' } as Record<number, string>,
    emptyChart: 'No visits in this period yet.',
    language: 'Language',
    topPages: 'Most visited pages',
    sources: 'Where visitors come from',
    direct: 'Direct',
    pages: { '/': 'Home', '/costs': 'Prices', '/stations': 'Stations' } as Record<string, string>,
  },
  prices: {
    title: 'Fuel prices',
    sub: "Changes appear on the site's prices page as soon as you save.",
    cardsTitle: 'Price cards',
    price: 'Price',
    unit: 'Unit',
    product: 'Product',
    label: 'Label',
    figure: 'Illustration',
    color: 'Color',
    kinds: { pump: 'Fuel pump', barrel: 'Barrel', gas: 'Gas cylinder' },
    tones: { dark: 'Dark', gold: 'Gold', blue: 'Blue' },
    addCard: 'Add a price card',
    invalidPrice: 'Enter numbers only, e.g. 350 or 4.60.',
    month: 'Month',
    value: '$ per barrel',
    newProduct: 'New product',
    blockedSave: 'Fix the highlighted fields to save.',
  },
  stations: {
    title: 'Stations',
    sub: "Stations listed on the site's stations page.",
    add: 'Add a station',
    name: 'Station name',
    area: 'Area',
    status: 'Status',
    description: 'Description',
    services: 'Services, one per line',
    empty: 'No stations yet. Add the first one.',
    newStation: 'New station',
    blockedSave: 'Every station needs a name in both languages.',
  },
}

export type Dict = typeof en

export const ar: Dict = {
  metaTitle: 'لوحة تحكم وتد',
  brand: { name: 'وتد للبترول', sub: 'لوحة التحكم' },
  nav: {
    overview: 'نظرة عامة',
    prices: 'الأسعار',
    stations: 'المحطات',
    viewSite: 'عرض الموقع',
    signOut: 'تسجيل الخروج',
    otherLang: 'English',
    menu: 'القائمة',
    closeMenu: 'إغلاق القائمة',
  },
  login: {
    title: 'تسجيل الدخول',
    sub: 'تابع زوار الموقع وعدّل الأسعار والمحطات.',
    password: 'كلمة المرور',
    submit: 'دخول',
    submitting: 'جارٍ الدخول…',
    wrong: 'كلمة المرور غير صحيحة.',
    tooMany: 'محاولات كثيرة. حاول مجدداً بعد بضع دقائق.',
    network: 'تعذر الاتصال بالخادم. تأكد أنه يعمل.',
  },
  common: {
    save: 'حفظ التغييرات',
    saving: 'جارٍ الحفظ…',
    saved: 'تم حفظ التغييرات',
    discard: 'تجاهل التغييرات',
    unsaved: 'لديك تغييرات غير محفوظة',
    allSaved: 'كل شيء محفوظ',
    delete: 'حذف',
    moveUp: 'نقل للأعلى',
    moveDown: 'نقل للأسفل',
    loading: 'جارٍ التحميل…',
    loadError: 'تعذر تحميل البيانات.',
    retry: 'إعادة المحاولة',
    saveError: 'تعذر الحفظ. تحقق من الاتصال وحاول مجدداً.',
    confirmDelete: 'هل تريد حذف هذا العنصر؟',
    arabic: 'العربية',
    english: 'الإنجليزية',
    noData: 'لا توجد بيانات بعد',
  },
  overview: {
    title: 'نظرة عامة',
    sub: 'زيارات الموقع العام. تتحدث الأرقام كل 30 ثانية.',
    refresh: 'تحديث',
    visitors: 'الزوار الفريدون',
    visitorsNote: 'كل متصفح يُحسب مرة واحدة',
    totalViews: 'مشاهدات الصفحات',
    totalViewsNote: 'منذ البداية',
    last7: 'آخر 7 أيام',
    today: 'اليوم',
    visitorsCount: '{n} زائر',
    chartTitle: 'الزيارات اليومية',
    series: { views: 'مشاهدات الصفحات', visitors: 'الزوار' },
    range: { 7: '7 أيام', 30: '30 يوماً', 90: '90 يوماً' },
    emptyChart: 'لا توجد زيارات في هذه الفترة بعد.',
    language: 'اللغة',
    topPages: 'الصفحات الأكثر زيارة',
    sources: 'من أين يأتي الزوار',
    direct: 'مباشر',
    pages: { '/': 'الرئيسية', '/costs': 'الأسعار', '/stations': 'المحطات' },
  },
  prices: {
    title: 'أسعار المحروقات',
    sub: 'تظهر التعديلات في صفحة الأسعار على الموقع فور الحفظ.',
    cardsTitle: 'بطاقات الأسعار',
    price: 'السعر',
    unit: 'الوحدة',
    product: 'المنتج',
    label: 'الوصف',
    figure: 'الرسم',
    color: 'اللون',
    kinds: { pump: 'مضخة وقود', barrel: 'برميل', gas: 'أسطوانة غاز' },
    tones: { dark: 'داكن', gold: 'ذهبي', blue: 'أزرق' },
    addCard: 'إضافة بطاقة سعر',
    invalidPrice: 'أدخل أرقاماً فقط، مثل 350 أو 4.60.',
    month: 'الشهر',
    value: 'دولار للبرميل',
    newProduct: 'منتج جديد',
    blockedSave: 'صحّح الحقول المحددة لتتمكن من الحفظ.',
  },
  stations: {
    title: 'المحطات',
    sub: 'المحطات المعروضة في صفحة المحطات على الموقع.',
    add: 'إضافة محطة',
    name: 'اسم المحطة',
    area: 'المنطقة',
    status: 'الحالة',
    description: 'الوصف',
    services: 'الخدمات، خدمة في كل سطر',
    empty: 'لا توجد محطات. أضف أول محطة.',
    newStation: 'محطة جديدة',
    blockedSave: 'يجب أن يكون لكل محطة اسم بالعربية والإنجليزية.',
  },
}
